name: arXiv Daily Email

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 运行脚本发邮件
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          FROM_EMAIL: "你的QQ邮箱@qq.com"
          TO_EMAIL: "123456@qq.com"
        run: python arxiv_daily.py